# hyprpaper.conf

wallpaper {
    # Monitor name or empty for all monitors
    monitor =

    # Path to the wallpaper image
    path = ~/.config/hypr/waylandx2.png

    # Set scaling mode: fill, fit, stretch, center, tile
    fit_mode = fill
}

# Optional: enable rendering of the hyprland splash over the wallpaper
# splash = true

# Optional: how far up should the splash be displayed
# splash_offset = 20

# Optional: how opaque the splash is
# splash_opacity = 0.8

# Optional: whether to enable IPC
# ipc = true
