# -----------------------------------------------------
# WINDOWS
# -----------------------------------------------------

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more


# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}



# nm-tray
windowrule {
  name = windowrule-3
  float = on
  border_size = 0
  match:class = ^(nm-tray)$
}

# windowrulev2 = nofocus, class:^(nm-tray)$
windowrule {
  name = windowrule-4
  float = on
  border_size = 0
  match:class = ^(Nm-applet|nm-applet)$
}

# windowrulev2 = nofocus, class:^(Nm-applet|nm-applet)$

# float the editor when it opens
windowrule {
  name = windowrule-5
  float = on
  match:class = ^(Nm-connection-editor|nm-connection-editor)$
}

# windowrulev2 = nofocus, class:^(Nm-connection-editor|nm-connection-editor)$

# new manager
windowrule {
  name = windowrule-6
  float = on
  match:title = ^(.*Network Manager.*)$
}

# steam
windowrule {
  name = windowrule-7
  float = on
  fullscreen = on
  border_size = 0
  immediate = on
  match:class = ^(steam_app_.*)$
}


# tearing
windowrule {
  name = windowrule-8
  immediate = on
  match:class = ^(cs2)$
}
